### ISSUE TITLE
For loop cannot have a declaration as the first field

### ISSUE THREAD

**Issue by KidusAM** [Bruk3/C-net#35]
For e.g. right now for(int i = 0; i < 5; i += 1) is not valid.

**Comment by Bruk3** [comment]
This is actually not specified by standard C. It's just some later versions of GCC compilers that allowed declarations in for loops

**Comment by Bruk3** [comment]
Check out: [https://stackoverflow.com/questions/1287863/c-for-loop-int-initial-declaration](c-for-loop-int-initial-declaration). 

But, it'd be a cool feature to have in our compiler
